'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    const newDate = new Date();
    await queryInterface.bulkInsert('state', [
      {
        name: 'Alabama',
        abbreviation: 'AL',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Alaska',
        abbreviation: 'AK',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Arizona',
        abbreviation: 'AZ',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Arkansas',
        abbreviation: 'AR',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'California',
        abbreviation: 'CA',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Colorado',
        abbreviation: 'CO',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Connecticut',
        abbreviation: 'CT',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Delaware',
        abbreviation: 'DE',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'District of Columbia',
        abbreviation: 'DC',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Florida',
        abbreviation: 'FL',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Georgia',
        abbreviation: 'GA',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Hawaii',
        abbreviation: 'HI',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Idaho',
        abbreviation: 'ID',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Illinois',
        abbreviation: 'IL',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Indiana',
        abbreviation: 'IN',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Iowa',
        abbreviation: 'IA',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Kansas',
        abbreviation: 'KS',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Kentucky',
        abbreviation: 'KY',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Louisiana',
        abbreviation: 'LA',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Maine',
        abbreviation: 'ME',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Maryland',
        abbreviation: 'MD',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Massachusetts',
        abbreviation: 'MA',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Michigan',
        abbreviation: 'MI',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Minnesota',
        abbreviation: 'MN',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Mississippi',
        abbreviation: 'MS',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Missouri',
        abbreviation: 'MO',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Montana',
        abbreviation: 'MT',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Nebraska',
        abbreviation: 'NE',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Nevada',
        abbreviation: 'NV',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'New Hampshire',
        abbreviation: 'NH',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'New Jersey',
        abbreviation: 'NJ',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'New Mexico',
        abbreviation: 'NM',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'New York',
        abbreviation: 'NY',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'North Carolina',
        abbreviation: 'NC',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'North Dakota',
        abbreviation: 'ND',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Ohio',
        abbreviation: 'OH',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Oklahoma',
        abbreviation: 'OK',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Oregon',
        abbreviation: 'OR',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Pennsylvania',
        abbreviation: 'PA',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Rhode Island',
        abbreviation: 'RI',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'South Carolina',
        abbreviation: 'SC',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'South Dakota',
        abbreviation: 'SD',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Tennessee',
        abbreviation: 'TN',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Texas',
        abbreviation: 'TX',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Utah',
        abbreviation: 'UT',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Vermont',
        abbreviation: 'VT',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Virginia',
        abbreviation: 'VA',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Washington',
        abbreviation: 'WA',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'West Virginia',
        abbreviation: 'WV',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Wisconsin',
        abbreviation: 'WI',
        created_at: newDate,
        updated_at: newDate,
      },
      {
        name: 'Wyoming',
        abbreviation: 'WY',
        created_at: newDate,
        updated_at: newDate,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('state', null, {});
  },
};
