export interface Rows {
  [index: string]: string | number | null;
  id: number;
  lastName: string;
  firstName: string | null;
  email: string | null;
  mobile: string | null;
  role: string | null;
  office: string | null;
  department: string | null;
}

export const rows: Array<Rows> = [
  {
    id: 1,
    lastName: 'Snow',
    firstName: '20Jon',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 2,
    lastName: 'Lannister',
    firstName: '3Cersei',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 3,
    lastName: 'Lannister',
    firstName: 'Jaime',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 4,
    lastName: 'Stark',
    firstName: 'Arya',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 5,
    lastName: 'Targaryen',
    firstName: 'Daenerys',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 6,
    lastName: 'Melisandre',
    firstName: null,
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 7,
    lastName: 'Clifford',
    firstName: 'Ferrara',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 8,
    lastName: 'Frances',
    firstName: 'Rossini',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 9,
    lastName: 'Roxie',
    firstName: 'Harvey',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 10,
    lastName: 'Snow',
    firstName: 'Jon',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 11,
    lastName: 'Snow',
    firstName: 'Jon',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 12,
    lastName: 'Lannister',
    firstName: 'Cersei',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 13,
    lastName: 'Lannister',
    firstName: 'Jaime',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 14,
    lastName: 'Stark',
    firstName: 'Arya',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 15,
    lastName: 'Targaryen',
    firstName: 'Daenerys',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 16,
    lastName: 'Melisandre',
    firstName: null,
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 17,
    lastName: 'Clifford',
    firstName: 'Ferrara',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 18,
    lastName: 'Frances',
    firstName: 'Rossini',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
  {
    id: 19,
    lastName: 'Roxie',
    firstName: 'Harvey',
    email: null,
    mobile: null,
    role: null,
    office: null,
    department: null,
  },
];
