import { Employee } from '../../../types/types';

export const rows: Array<Employee> = [
  {
    id: 1,
    lastName: 'Snow',
    firstName: '20Jon',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 2,
    lastName: 'Lannister',
    firstName: '3Cersei',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 3,
    lastName: 'Lannister',
    firstName: 'Jaime',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 4,
    lastName: 'Stark',
    firstName: 'Arya',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 5,
    lastName: 'Targaryen',
    firstName: 'Daenerys',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 6,
    lastName: 'Melisandre',
    firstName: 'Cool',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 7,
    lastName: 'Clifford',
    firstName: 'Ferrara',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 8,
    lastName: 'Frances',
    firstName: 'Rossini',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 9,
    lastName: 'Roxie',
    firstName: 'Harvey',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 10,
    lastName: 'Snow',
    firstName: 'Jon',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 11,
    lastName: 'Snow',
    firstName: 'Jon',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 12,
    lastName: 'Lannister',
    firstName: 'Cersei',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 13,
    lastName: 'Lannister',
    firstName: 'Jaime',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 14,
    lastName: 'Stark',
    firstName: 'Arya',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 15,
    lastName: 'Targaryen',
    firstName: 'Daenerys',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 16,
    lastName: 'Melisandre',
    firstName: 'Cool',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 17,
    lastName: 'Clifford',
    firstName: 'Ferrara',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 18,
    lastName: 'Frances',
    firstName: 'Rossini',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
  {
    id: 19,
    lastName: 'Roxie',
    firstName: 'Harvey',
    email: 't@gmail.com',
    mobile: '6666666666',
  },
];
